import type{Stage}from"./firestore/types";
export const STAGES:Stage[]=["Initiated","Script Writing","Storyboarding","Recording","Editing","Review","Done"];
export const STAGE_BG:Record<Stage,string>={"Initiated":"#E5E4DC","Script Writing":"#FAC775","Storyboarding":"#CECBF6","Recording":"#F5C4B3","Editing":"#B5D4F4","Review":"#9FE1CB","Done":"#C0DD97"};
export const STAGE_TEXT:Record<Stage,string>={"Initiated":"#444441","Script Writing":"#633806","Storyboarding":"#3C3489","Recording":"#712B13","Editing":"#0C447C","Review":"#085041","Done":"#27500A"};
export const SCRIPT_SECTIONS=["Title Card","Intro Hook","Problem Statement","Solution Narrative","Demo Walkthrough","People Segment","Results & Impact","Outro & CTA"];
export const STORYBOARD_SECTIONS=["Title Card","Intro Animation","Problem Visual","Solution Illustration","Demo Clip","Interview Segment","Results Screen","Outro Card"];
export const MEMBER_COLORS=["#CECBF6","#9FE1CB","#FAC775","#F5C4B3","#B5D4F4","#C0DD97","#F4C0D1","#D3D1C7"];
export const MEMBER_TEXT_COLORS=["#3C3489","#085041","#633806","#712B13","#0C447C","#27500A","#72243E","#444441"];
export const ROLES=["writer","editor","manager","director"] as const;
export const stagePct=(s:Stage)=>Math.round((STAGES.indexOf(s)/Math.max(STAGES.length-1,1))*100);
export const sectionPct=(sec:Record<string,boolean>,list:string[])=>list.length===0?0:Math.round(list.filter(s=>sec[s]).length/list.length*100);